// <auto-generated />
using EZ.WebAPI.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace EZ.WebAPI.Migrations
{
    [DbContext(typeof(AppDbContext))]
    partial class AppDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.0-rtm-30799")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("EZ.WebAPI.Models.Employee", b =>
                {
                    b.Property<string>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("Birth_Date");

                    b.Property<string>("Cost_Center");

                    b.Property<string>("Cost_Center_HoD");

                    b.Property<string>("Department");

                    b.Property<string>("Dept_Head_Email");

                    b.Property<string>("Dept_Head_Name");

                    b.Property<string>("Dept_Head_Name_AP");

                    b.Property<string>("Dept_Head_No");

                    b.Property<string>("Division");

                    b.Property<string>("E_Mail");

                    b.Property<string>("Emp_ID");

                    b.Property<string>("Employee_Name_Arabic");

                    b.Property<string>("Employee_Name_English");

                    b.Property<string>("Employee_Spouse");

                    b.Property<string>("Function_Head");

                    b.Property<string>("Gender");

                    b.Property<string>("Grade");

                    b.Property<string>("Hiring_Date");

                    b.Property<string>("ID_Iqama");

                    b.Property<string>("Line_Manager_Email");

                    b.Property<string>("Line_Manager_Name");

                    b.Property<string>("Line_Manager_Name_AP");

                    b.Property<string>("Line_Manager_No");

                    b.Property<string>("Mobile");

                    b.Property<string>("Nationality");

                    b.Property<string>("Oracle_Org_Name");

                    b.Property<string>("Position");

                    b.Property<string>("PositionArabic");

                    b.Property<string>("Section");

                    b.Property<string>("Sponsor");

                    b.Property<string>("Termination_Date");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });
#pragma warning restore 612, 618
        }
    }
}
